### PR TITLE
Fixing loop setting.

### LINKED ISSUE #534: can't seek after exiting zoom with mouse back button
from https://github.com/commaai/connect/pull/486. back button in the UI works though

https://github.com/commaai/connect/assets/25857203/3f5785b8-4f9f-40a8-b536-cbd45d7a7e0b

### PR DESCRIPTION
**Pull request by 0x7B5**
Fixes #534

### CODE REVIEW

File: src/reducers/globalState.js [hunk 1]
```diff
@@ -306,6 +306,11 @@ export default function reducer(_state, action) {
             end: state.currentRoute.duration,
             previous: state.zoom,
           }
+
+          state.loop = {
+            startTime: state.zoom.start,
+            duration: state.zoom.end - state.zoom.start,
+          };
```
Comment (sshane) [inline src/reducers/globalState.js]: I believe this is only masking over the problem, in that `popTimelineRange` isn't used the same way when using the browser back buttons, but adding an event listener seems to make the behavior even more buggy

**Comment by sshane** [comment]
this is also a reminder that we should not have `zoom` and `loop` in [new-connect](https://github.com/commaai/new-connect) @incognitojam. I haven't taken a real look into why we need each, but surface level it seems that they are very similar, confusing to work with, and can be combined in most cases
